### ISSUE TITLE
Please acknowledge that 3 different permissions required

### ISSUE THREAD

**Issue by news2tomorrow** [leorigna/SlimSocial-for-Facebook#7]
You claim
>SlimFacebook, with its 1.1Mb 680Kb and 0 Permissions, is the result! Just made, anyone who has saw it want to download it 

It is not 0 permissions. Your app needs 
>    
    
    <uses-permission android:name="android.permission.INTERNET"/>
    
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

Please rewrite your description. Thanks.

**Comment by leorigna** [comment]
Initially it had only the permission to connect to internet that is the minium for work.
After someone has asked me to add upload of photos and gps.
I'm going to update the description.
